# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LXXTLpP4ZxPVh30czSduQqe9kVo6afLO
"""

import pandas as pd

# Estimated team velocity
sprint_size=100

# Load product backlog containing estimated story point and priority values
df=pd.read_csv("/content/moodleprio.csv")
sp_per_prio=df.storypoint/df.priority
df['effort_per_prio']=sp_per_prio
# Suggest refinement where the issue is too large compared to team velocity
df['Refinement']="-"
df.loc[df['storypoint'] > 0.25*sprint_size, 'Refinement'] = "Refine"   
display(df[0:10])

# Sorting
efficient_backlog=df.sort_values('effort_per_prio', axis = 0, ascending = True, inplace = False) 
display(efficient_backlog[0:10])
prio_backlog=df.sort_values('priority', axis = 0, ascending = False, inplace = False)
display(prio_backlog[0:10])

# Creating efficient sprint backlog
sp_sum=0
ind=0

while sp_sum<sprint_size:
    sp_sum+=efficent_backlog.iloc[ind,3]  #summing storypoints
    ind+=1
efficient_sprint=efficient_backlog[0:ind-1]
print(efficient_sprint)

# Creating prioritized sprint backlog
sp_sum=0
ind=0

while sp_sum<sprint_size:
    sp_sum+=prio_backlog.iloc[ind,3]      #summing storypoints
    ind+=1
prio_sprint=prio_backlog[0:ind-1]
print(prio_sprint)